### ISSUE TITLE
Can not use this font, setting failed

### ISSUE THREAD

**Issue by ssrlive** [delinx/ExcelsiorRoboto#1]
Please fix this issue.

![image](https://user-images.githubusercontent.com/30760636/221079270-ece11211-85ae-4f29-9ba6-8e35d8f4e12d.png)

**Comment by delinx** [comment]
Hey ssrlive, please use Windows compatible version! 
[FixedsysModernV05.Nerd.Font.Complete.Mono.Windows.Compatible.ttf](https://github.com/delinx/Fixedsys-Modern/releases/download/v5/FixedsysModernV05.Nerd.Font.Complete.Mono.Windows.Compatible.ttf)
`FixedsysModernV05 NFM`
