### ISSUE TITLE
Roundness of exclamation mark and parenthesis characters

### ISSUE THREAD

**Issue by Ferk** [delinx/ExcelsiorRoboto#2]
First of all, Thanks for the project. I think this is a very interesting idea!

However, I've noticed a couple of characters that I think could be improved still, to better match the original FixedSys.

1. The exclamation mark isn't as "round" in Fixedsys-Modern as in the original. The original one was clearly distinguishable because of the big slope, making it feel more "chubby" and making it stand out more among other punctuation marks.

2. I feel the curvature of the parenthesis along the ends is also not the same in the modern version. The original parenthesis ended in a 1 pixel tip, almost like a curved claw that is thicker in the center and thinner on the ends. It feels as if the modern version is a more homogeneous line, and it leaves a more open curvature that ends in a cut, as if you could extend the ends and result in a huge curve, whereas in the original symbols it's almost like the endings were starting to close the sides of an ellipse, so even if you were to extend it, the line would not go as far vertically.

I wish I could try and experiment with this myself and maybe open a PR for the change. But I see that this project seems to rely on Affinity Designer (it looks like it uses an `afdesign` file there), which I do not own.

See below table for comparison, with "o" for "original" and "m" for "modern".

| o | m |
|---|---|
| <img src="https://github.com/delinx/Fixedsys-Modern/assets/193426/7c92a745-de99-4cc3-a282-54a193a22e12"  width="32"> | <img src="https://github.com/delinx/Fixedsys-Modern/raw/0c86bf7a7/Characters/chars/Special/!.svg"  width="46" height="46"> |
| <img src="https://github.com/delinx/Fixedsys-Modern/assets/193426/8860a45a-c35a-4717-83ae-2ef1fd57a390"  width="32"> | <img src="https://github.com/delinx/Fixedsys-Modern/raw/0c86bf7a7/Characters/chars/Special/(.svg"  width="48" height="48"> |
| <img src="https://github.com/delinx/Fixedsys-Modern/assets/193426/bd6c12a9-f0ed-40dd-9c5a-cc1db49fbca8"  width="32"> | <img src="https://github.com/delinx/Fixedsys-Modern/raw/0c86bf7a7/Characters/chars/Special/).svg"  width="55" height="55"> |

**Comment by delinx** [comment]
Hey, thanks for your feedback! I agree entirely! However, I currently do not have time to work on this (just got a new job). These days I mostly use Berkeley Mono, but I still miss fixedsys, to be completely honest ): 

Initially, I was very happy with this attempt at making a font (never done this before). However, numerous rendering issues eventually got to me, and I didn't have the time or experience to address them in a sensible way.

I used a commercial product I don't have access to anymore to generate the font out of SVG images (my mistake, but this was meant to be a prototype), so I cannot re-generate font anymore.

However, someone with knowledge of [FontForge](https://fontforge.org/en-US/) (or alike programs) could make those changes rather easily to both TTF and OTF.

I included my SVG project, if you import it into Inkscape, it even preserves layers and their naming!

[VectorDesign](https://github.com/delinx/Fixedsys-Modern/assets/6831935/c8d4f640-9028-4ae2-942f-aa53b0f39a4d)

Sorry for not being able to provide more support on this matter, feel free to offer a PR or clone the project if you wish, I would love a modern version of Fixedsys to exist.

PS. I was thinking of potentially paying someone to design it, but it's in a ballpark of 2,000$ at its lowest, maybe if there are enough people interested its possible to crowdfund it? No idea, its a bit of a wild idea.

**Comment by delinx** [comment]
After sitting on the idea for a bit, I am actually thinking of giving this another go and trying to design it entirely from scratch (I used Fixedsys as a file in the generation before, so all symbols I did not draw are original Fixedsys, and it led to some issues with rendering I think). 

So depending on how much in a rush you are, feel free to let it sit for a few days and see if I make any progress.

**Comment by delinx** [comment]
@Ferk Little preview of a new version I have been working on. Do you reckon this looks better?
In the last few days, I basically re-draw the entire font (alphas, special symbols and numerics), I still need to figure out some export settings and add the original Fixedsys as a fallback to import all missing symbols. 

![image](https://github.com/delinx/Fixedsys-Modern/assets/6831935/be15b101-32f5-4e34-b23c-402768b913a2)
![image](https://github.com/delinx/Fixedsys-Modern/assets/6831935/bef62350-ab57-4008-83c6-65daee52e670)

**Comment by delinx** [comment]
Still need to fix a few bugs, but generally, I love how it looks/feels
(I don't like the current 'r', and the offset of '1' was wrong. 

![image](https://github.com/delinx/Fixedsys-Modern/assets/6831935/c1ba4820-888f-412e-8609-32fdd477d810)
![image](https://github.com/delinx/Fixedsys-Modern/assets/6831935/027d07d1-a8df-45f6-822f-5249ee1d3c51)

**Comment by delinx** [comment]
Forgive my spelling, I am rather tired. 
![image](https://github.com/delinx/Fixedsys-Modern/assets/6831935/939cfea2-377a-4036-9d55-bdddb4ffe1d9)
Improved 'r' shape and fixed '1' spacing, 

![image](https://github.com/delinx/Fixedsys-Modern/assets/6831935/509bb66a-c5aa-4844-9b9b-7fa66c5a7822)
![image](https://github.com/delinx/Fixedsys-Modern/assets/6831935/568f8ae2-9445-4e8e-a3fb-1ab0e2d34525)

**Comment by delinx** [comment]
Published an updated version, if you got any feedback feel free to open a new issue.

**Comment by Ferk** [comment]
Whoa! thanks!
I think it looks a lot more consistent and cleaner.

**Comment by delinx** [comment]
@Ferk Thank you, I appreciate it! There is a surprising amount of settings within fonts; hopefully, as time goes on, I can slowly nail different aspects down.
